galaxy:
  jobs:
    rules:
      tpv_rules_local.yml:
        tools:  
          toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/.*:
            cores: 10
            mem: 50
          toolshed.g2.bx.psu.edu/repos/devteam/cufflinks/cufflinks/.*:
            cores: 6
            mem: 32
        